#!/usr/bin/zsh
################################################################################
# $Id: optparser 2025-04-15 16:21:04 +0200 .m0rph $
################################################################################
# Description:
#  A little shell script option parser template.
#
#  This template uses the zsh module zparseopts with optional opts setting.
#  Different from the builtin function getopts or GNU getopt, we can simply
#  validate 'empty options' that should carry an argument, because with two
#  colons zparseopts stores the option itself AND its argument in the same 
#  array element. So can simply validate it, or rub it out via parameter
#  expansion.
#
################################################################################

print_error() {
   typeset -A errmsg
   errmsg=(
      [u]='Error: Parameter -u needs an URL. Exiting !!!'
      [o]='Error: Parameter -o needs a filename. Ingnoring.'
      [h]='Error: Parameter -u needs at least one HTTP header. Ignoring.'
   )
   print -l -- "${errmsg[$1]}"
}

typeset -a url
typeset -a outfile
typeset -a headers

zparseopts -D -E u::=url o::=outfile h::=headers
[[ $outfile == '-o' ]] && print_error 'o'
[[ $headers == '-h' ]] && print_error 'h'
[[ $url     == '-u' ]] && {
   print_error 'u'
   exit 1
}
print -l -- 'URL: '${url/-u/}
print -l -- 'OUTFILE: '${outfile/-o/}
print -l -- 'HEADERS: '${headers/-h/}

exit 0
